### ISSUE TITLE
Model Building/Evaluation

### ISSUE THREAD

**Issue by Carol-Kelly** [Carol-Kelly/Hamoye-Data-Warehouse-ProjectTeam#17]

**Comment by Duks31** [comment]
The Data is small, the model will not work, but i have Linear Regression Analysis

**Comment by Carol-Kelly** [comment]
@Duks31 How did you go about the Linear Regression Analysis?

**Comment by Duks31** [comment]
OK So, 

Firstly i found the earning gap per job title ( ie for example managers; the difference between the malemanagers and the femalemanagers ) then i did a regression plot. 

I didnt even have to use the sklearn Linear Regression Library 

Seaborn Lineplot ( lmplot ) could so it already. And yes seaborn has regplot ( Regression plot ) but also did research and found out that the Lineplot combines regplot and FacetGrid 

The FacetGrid class helps in visualizing the distribution of one variable as well as the relationship between multiple variables separately within subsets of your dataset using multiple panels. 

But withstanding the difference i did the analysis with the two ( regplot and lmplot ) and it was same.

**Comment by Carol-Kelly** [comment]
Then, it means your analysis will be added to the EDA.

**Comment by Duks31** [comment]
Most likely

**Comment by Heartz00** [comment]
is this not where we are to discuss the time series model

**Comment by Duks31** [comment]
Probably for both

**Comment by Carol-Kelly** [comment]
@Heartz00 It's for both discussions

**Comment by Heartz00** [comment]
okay thanks , i have gone through the data, and i dont see how any form of modelling could work for a dataset less than 400, atleast not the models i thought of, and i even try upsampling the data for time series analysis, just did not make sense to me, i will agree with the linear regression analysis proposed by chidubem

**Comment by Duks31** [comment]
No Problem then.

So the time series analysis didnt bring out anything ?

**Comment by Heartz00** [comment]
for me , but i do not know if other partners found something

**Comment by Duks31** [comment]
OK 
No problem

**Comment by Carol-Kelly** [comment]
It seems everyone is working independently.

**Comment by Duks31** [comment]
Not Really 

I mean atleast i have had a meeting with someone in regression, not many people showed up but i passed across the information 

Regardless, the whatsapp group has been a little quiet on the model talking so its hard to know whats guys are upto

**Comment by Carol-Kelly** [comment]
I'm talking mainly about the time series team
