### ISSUE TITLE
Conversion of year to job title

### ISSUE THREAD

**Issue by CorazonAkinyi** [Carol-Kelly/Hamoye-Data-Warehouse-ProjectTeam#8]
Could we give an explanation or rationale behind this decision??

**Comment by Carol-Kelly** [comment]
@CorazonAkinyi The dataset was transposed such that the various years from 2004-2017 became columns along with the job title.

**Comment by Duks31** [comment]
Explanation will be nice

**Comment by Carol-Kelly** [comment]
@Duks31 I've already done that above. More clarifications will be given in the meeting if needed.
